export const translations = {
    zh: {
        // Header
        yearOfCode: "代码之年",
        profileVersion: "档案版本",

        // Metrics
        activeDays: "活跃天数",
        activeDaysSubtext: "有代码提交的日子",
        totalContributions: "总贡献数",
        peakDay: "单日峰值",
        newProjects: "新建项目",
        newProjectsSubtext: "创建并提交",
        mostUsedLanguage: "最常用语言",
        acrossRepos: "个仓库",

        // Collaboration
        codeReviews: "代码审查",
        reviewsSubtext: "审查的 PR",
        prsCreated: "创建的 PR",
        mergedRate: "合并率",

        // Behaviors
        focusScore: "专注度",
        focusCaption: "基于核心仓库占比",
        consistency: "一致性",
        consistencyCaption: "基于活跃天数连续性",
        collaboration: "协作力",
        collaborationCaption: "基于 PR 和评审互动",
        burstiness: "爆发力",
        burstinessCaption: "基于提交活动的波动性",
        peakTime: "活跃时段",
        Morning: "晨间",
        Afternoon: "午后",
        Evening: "晚间",
        Night: "深夜",
        Daytime: "日间",

        // Narrative
        engineeringNarrative: "工程师画像",
        generatingSummary: "正在生成总结...",
        reportGenerating: "报告正在生成中...",

        // Footer
        generatedBy: "由 Year of Code 生成",

        // Loading
        analyzingDNA: "分析工程 DNA",
        processingEvents: "在浏览器中本地处理 GitHub 事件...",
        systemLogs: "系统日志",

        // Input
        annualReport: "年度报告",
        decodeEngineeringDNA: "解码你的工程 DNA",
        githubToken: "GitHub Token",
        llmBaseUrl: "LLM 基础 URL",
        llmApiKey: "LLM API Key",
        llmModel: "LLM 模型",
        year: "年份报告",
        language: "语言选择",
        generateProfile: "生成档案",
        requiresScopes: "需要",
        andScopes: "和",
        scopes: "权限",
        tokensProcessedLocally: "Token 仅在本地处理",
        pipelineError: "流水线错误",
        retry: "重试"
    },
    en: {
        // Header
        yearOfCode: "Year of Code",
        profileVersion: "Profile Version",

        // Metrics
        activeDays: "Active Days",
        activeDaysSubtext: "Days you pushed code",
        totalContributions: "Total Contributions",
        peakDay: "Peak",
        newProjects: "New Projects",
        newProjectsSubtext: "Created & Committed",
        mostUsedLanguage: "Most Used Language",
        acrossRepos: "repos",

        // Collaboration
        codeReviews: "Code Reviews",
        reviewsSubtext: "PRs reviewed",
        prsCreated: "PRs Created",
        mergedRate: "merged rate",

        // Behaviors
        focusScore: "Focus Score",
        focusCaption: "Based on top repo dominance",
        consistency: "Consistency",
        consistencyCaption: "Based on active day streak",
        collaboration: "Collaboration",
        collaborationCaption: "Based on reviews & PRs",
        burstiness: "Burstiness",
        burstinessCaption: "Based on activity variance",
        peakTime: "Peak Time",
        Morning: "Morning",
        Afternoon: "Afternoon",
        Evening: "Evening",
        Night: "Night",
        Daytime: "Daytime",

        // Narrative
        engineeringNarrative: "Engineering Narrative",
        generatingSummary: "Generating your summary...",
        reportGenerating: "Report is generating...",

        // Footer
        generatedBy: "Generated by Year of Code",

        // Loading
        analyzingDNA: "Analyzing Engineering DNA",
        processingEvents: "Processing GitHub events locally in your browser...",
        systemLogs: "System Logs",

        // Input
        annualReport: "Annual Report",
        decodeEngineeringDNA: "Decode your engineering DNA.",
        githubToken: "GitHub Token",
        llmBaseUrl: "LLM Base URL",
        llmApiKey: "LLM API Key",
        llmModel: "LLM Model",
        year: "Year",
        language: "Language",
        generateProfile: "Generate Profile",
        requiresScopes: "Requires",
        andScopes: "and",
        scopes: "scopes",
        tokensProcessedLocally: "Tokens are processed locally",
        pipelineError: "Pipeline Error",
        retry: "Retry"
    }
};
